### PR TITLE
packaging: Do not build for i586 and s390

### PR DESCRIPTION
**Pull request by DimStar77**

### CODE REVIEW

**Review by dgdavid — COMMENTED** [review]
Thanks for taking care about it @DimStar77. And sorry for the delayed review :sweat_smile: 

I miss a bug reference in the changelog. Do you have any?

Thanks!

**Comment by DimStar77** [comment]
No bug report - just went through unresolvable builds on openSUSE:Factory

**Comment by DimStar77** [comment]
bug ref added

**Review by dgdavid — APPROVED** [review]
LGTM

**Pull request merged**
